site_name: MrClock's tool documentations
theme:
  name: readthedocs
  highlightjs: true
  logo: img/logo.png
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - toc:
      permalink: true
      baselevel: 1
nav:
    - Home: 'index.md'
    - Python:
        - 'python/colorconverter.md'
    - Visual Basic .Net:
        - 'vbnet/colorconverter.md'
        - 'vbnet/colorlibrary.md'
    - Visual Basic .Net Framework:
        - 'vbnetframework/colorlibrary.md'
    - Formats:
        - 'formats/libraryTXT.md'
        - 'formats/libraryXML.md'
        - 'formats/colorlib.md'